[versions]
# plugins
shadow = "8.3.5"
indra = "3.1.3"
toxopid = "4.1.2"
spotless = "6.25.0"
errorprone-gradle = "4.0.1"

# utilities
slf4md = "1.0.1"
distributor = "4.2.0-SNAPSHOT"

# static analysis
errorprone-core = "2.36.0"
nullaway = "0.11.3"
jspecify = "1.0.0"

[libraries]
# utilities
distributor-api = { module = "com.xpdustry:distributor-common-api", version.ref = "distributor" }

# static analysis
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

[plugins]
indra-common = { id = "net.kyori.indra", version.ref = "indra" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
toxopid = { id = "com.xpdustry.toxopid", version.ref = "toxopid" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone-gradle = { id = "net.ltgt.errorprone", version.ref = "errorprone-gradle" }
